### ISSUE TITLE
Loading TextEmbeds that include negitive CFG fails

### ISSUE THREAD

**Issue by CambridgeComputing** [kijai/ComfyUI-HunyuanVideoWrapper#142]
I've been using the new `TextEmbeds Save` node to generate the text embedding on one PC, while performing the actual video inferencing on another. This works great _except_ when I use the `HunyuanVideo CFG` node to try and add negative embeddings to the process. I've confirmed that there are no other conflicts by simply disabling this node, transferring the saved embedding, and loading it into my video workflow. That works every time, but adding in the extra node causes it to fail. The error I get is
```
TypeError: expected Tensor as element 0 in argument 0, but got NoneType
```

I've also attached the ComfyUI log if needed. As always, if you point me in the right direction, I'm absolutely wiling to make the code changes and submit a pull request if you'd like. Otherwise, thanks for all you do for the this awesome community!

[error.txt](https://github.com/user-attachments/files/18134327/error.txt)

**Comment by kijai** [comment]
With the nodes at latest version? It's working for me.

**Comment by kijai** [comment]
Maybe this is actually about using clip_l with cfg, I hadn't added the negative prompt encoding for that use case, should work now.

**Comment by CambridgeComputing** [comment]
I've updated this plugin as well as the main ComfyUI repo. I tried creating a TextEmbed, but got the following error:
```
cannot access local variable 'negative_prompt_embeds_2' where it is not associated with a value
```

I've attached the workflow I'm using here, but it's pretty basic.

NOTE: This workflow works, but only if I include the `HunyuanVideo CFG` node. However when I use that TextEmbed (with the negative embeds) on another computer, I get the following error when trying to generate a video:
```
Traceback (most recent call last):
  File "/home/dennism/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dennism/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dennism/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/dennism/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dennism/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/nodes.py", line 1089, in process
    out_latents = model["pipe"](
                  ^^^^^^^^^^^^^^
  File "/home/dennism/miniconda3/envs/comfyui/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dennism/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 593, in __call__
    raise NotImplementedError
NotImplementedError
```

[te_test.json](https://github.com/user-attachments/files/18137696/te_test.json)

**Comment by kijai** [comment]
> I've updated this plugin as well as the main ComfyUI repo. I tried creating a TextEmbed, but got the following error:
> ```
> cannot access local variable 'negative_prompt_embeds_2' where it is not associated with a value
> ```
> 
> I've attached the workflow I'm using here, but it's pretty basic.
> 
> NOTE: This workflow works, but only if I include the `HunyuanVideo CFG` node. However when I use that TextEmbed (with the negative embeds) on another computer, I get the following error when trying to generate a video:
> ```
> Traceback (most recent call last):
>   File "/home/dennism/ComfyUI/execution.py", line 323, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/dennism/ComfyUI/execution.py", line 198, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/dennism/ComfyUI/execution.py", line 169, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "/home/dennism/ComfyUI/execution.py", line 158, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/dennism/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/nodes.py", line 1089, in process
>     out_latents = model["pipe"](
>                   ^^^^^^^^^^^^^^
>   File "/home/dennism/miniconda3/envs/comfyui/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/dennism/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 593, in __call__
>     raise NotImplementedError
> NotImplementedError
> ```
> 
> [te_test.json](https://github.com/user-attachments/files/18137696/te_test.json)
> 
> 
This one should be fixed now.

**Comment by CambridgeComputing** [comment]
@kijai Unfortunately, even after updating the plugin and Comfy on both computers, I'm still getting the `NotImplementedError` error when trying to generate videos using a text embedding that has a negative prompt. Removing the HunyuanVideo CFG node does allow the workflows to proceed, but I'm still unable to use that node. Let me know if you need any logs or further testing. Thank you!

**Comment by CambridgeComputing** [comment]
I actually found the issue. It looks like you can't use the STG node in conjunction with negative prompts. Disabling this node fixed it for now. My clue was on [this](https://github.com/kijai/ComfyUI-HunyuanVideoWrapper/blob/ecae5f270e7fda1ceff4490aa40dc6c9ff3ee8ad/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py#L591) line, so perhaps changing that or just dropping the negative embedding if they are incompatible? Sorry, I tried to come up with an actual code fix here but I'm short on time today.
